name: BuildAndPublish
description: 'Build a .NET project and publish the .nupkg to the feed'
inputs:
  SolutionName: 
      description: 'Name of the Solution'
      required: true
  BuildSolutionType:
    desciption: 'Build Configuration switch.'
    default: 'Release'
  Token:
    description: 'NugetToken'

runs:
  using: "composite"
  
  steps:
  - uses: actions/checkout@v3
  
  - name: Setup Nuget
    uses: NuGet/setup-nuget@v1.0.5

  - name: Setup .NET
    uses: actions/setup-dotnet@v2
    with:
      dotnet-version: 5.0.x
      
  - name: Restore dependencies
    run: nuget restore ${{ inputs.SolutionName }}
    shell: bash
    
  - name: Build
    run: dotnet build ${{ inputs.SolutionName }} --configuration ${{ inputs.BuildSolutionType }} --no-restore
    shell: bash
    
  - name: Pack
    id: PackForNuget
    run: dotnet pack --configuration ${{ inputs.BuildSolutionType }}
    shell: bash
    
  - name: Find nupkg
    id: FindNugetPackage
    uses: DovnarAlexander/github-action-file-detection@master
    with:
      wildcard: '*.nupkg'

  - name: Put To Nuget - from found nupkg
    if: inputs.PathToPackage == 'unknown'
    run: dotnet nuget push "${{ steps.FindNugetPackage.outputs.found }}" --api-key ${{ inputs.Token }} --source "github"
    shell: bash
